[pytest]
DJANGO_SETTINGS_MODULE = Vraa.settings
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --tb=short -v
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
testpaths = main/tests main
