# Generated by Django 4.2.27 on 2026-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_add_comment_model"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="main_commen_created_c43ef2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["message"], name="main_commen_message_35f0f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author"], name="main_commen_author__c512fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["-created_at"], name="main_messag_created_9aee2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["author"], name="main_messag_author__68dda8_idx"
            ),
        ),
    ]
