# Generated by Django 4.2.27 on 2026-01-24 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0003_add_database_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start dato")),
                ("end_date", models.DateField(verbose_name="Slut dato")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Afventer"),
                            ("confirmed", "Bekræftet"),
                            ("cancelled", "Annulleret"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Eventuelle bemærkninger til bookingen",
                        max_length=500,
                        verbose_name="Noter",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Opdateret"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bruger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookinger",
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date"], name="main_bookin_start_d_9ec413_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="main_bookin_end_dat_529aaf_idx"
                    ),
                    models.Index(
                        fields=["status"], name="main_bookin_status_f13d12_idx"
                    ),
                    models.Index(
                        fields=["user"], name="main_bookin_user_id_4be33e_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="end_date_after_start_date",
            ),
        ),
    ]
