# Generated by Django 4.2.27 on 2026-02-03 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_add_booking_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("comment", "Ny kommentar"),
                            ("booking_approved", "Booking godkendt"),
                            ("booking_rejected", "Booking afvist"),
                            ("mention", "Du blev nævnt"),
                            ("reply", "Svar på din kommentar"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titel")),
                ("message", models.TextField(max_length=500, verbose_name="Besked")),
                (
                    "link",
                    models.CharField(blank=True, max_length=200, verbose_name="Link"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Læst")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oprettet"),
                ),
            ],
            options={
                "verbose_name": "Notifikation",
                "verbose_name_plural": "Notifikationer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-is_pinned", "-pinned_at", "-created_at"],
                "verbose_name": "Besked",
                "verbose_name_plural": "Beskeder",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Fastgjorte beskeder vises øverst på opslagstavlen",
                verbose_name="Fastgjort",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="pinned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fastgjort tidspunkt"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="pinned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Fastgjort af",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["-is_pinned", "-pinned_at", "-created_at"],
                name="main_messag_is_pinn_659483_idx",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bruger",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"], name="main_notifi_user_id_4211ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="main_notifi_user_id_844422_idx"
            ),
        ),
    ]
