# Generated by Django 4.2.27 on 2026-02-04 06:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_notification_alter_message_options_message_is_pinned_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("referat", "Referat"),
                            ("vedtaegt", "Vedtægt"),
                            ("other", "Andet"),
                        ],
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=main.models.document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx"]
                            )
                        ],
                        verbose_name="Fil",
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        help_text="Datoen for dokumentet (f.eks. dato for generalforsamling)",
                        verbose_name="Dokument dato",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Beskrivelse"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploadet"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploadet af",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumenter",
                "ordering": ["-document_date"],
                "indexes": [
                    models.Index(
                        fields=["category", "-document_date"],
                        name="main_docume_categor_959552_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("booking_approved", "Booking godkendt"),
                            ("booking_rejected", "Booking afvist"),
                            ("user_activated", "Bruger aktiveret"),
                            ("user_deactivated", "Bruger deaktiveret"),
                            ("message_deleted", "Besked slettet"),
                            ("document_uploaded", "Dokument uploadet"),
                            ("document_deleted", "Dokument slettet"),
                        ],
                        max_length=30,
                        verbose_name="Handling",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        help_text="Model name of the affected object",
                        max_length=50,
                        verbose_name="Måltype",
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        help_text="Primary key of the affected object",
                        verbose_name="Mål-ID",
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Detaljer"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-adresse"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tidspunkt"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bruger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktivitetslog",
                "verbose_name_plural": "Aktivitetslogs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="main_auditl_created_aec285_idx"
                    ),
                    models.Index(
                        fields=["action"], name="main_auditl_action_1aa6dc_idx"
                    ),
                    models.Index(
                        fields=["user"], name="main_auditl_user_id_e1f16c_idx"
                    ),
                ],
            },
        ),
    ]
