# Generated by Django 4.2.27 on 2026-02-04 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0006_document_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("booking_approved", "Booking godkendt"),
                    ("booking_rejected", "Booking afvist"),
                    ("user_activated", "Bruger aktiveret"),
                    ("user_deactivated", "Bruger deaktiveret"),
                    ("message_deleted", "Besked slettet"),
                    ("document_uploaded", "Dokument uploadet"),
                    ("document_deleted", "Dokument slettet"),
                    ("maintenance_created", "Vedligeholdelsesanmodning oprettet"),
                    ("maintenance_updated", "Vedligeholdelsesanmodning opdateret"),
                ],
                max_length=30,
                verbose_name="Handling",
            ),
        ),
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(max_length=2000, verbose_name="Beskrivelse"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Hvor på ejendommen er problemet?",
                        max_length=100,
                        verbose_name="Placering",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Lav"),
                            ("medium", "Normal"),
                            ("high", "Høj"),
                            ("urgent", "Akut"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Prioritet",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Afventer"),
                            ("in_progress", "Under behandling"),
                            ("resolved", "Løst"),
                            ("wont_fix", "Afvist"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Interne noter fra administrator",
                        max_length=1000,
                        verbose_name="Admin noter",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Opdateret"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Løst"),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Indberetter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vedligeholdelsesanmodning",
                "verbose_name_plural": "Vedligeholdelsesanmodninger",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="main_mainte_created_7b6b75_idx"
                    ),
                    models.Index(
                        fields=["status"], name="main_mainte_status_60f5a6_idx"
                    ),
                    models.Index(
                        fields=["reporter"], name="main_mainte_reporte_052775_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="main_mainte_priorit_e4781c_idx"
                    ),
                ],
            },
        ),
    ]
