# Generated by Django 4.2.27 on 2026-02-04 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0007_alter_auditlog_action_maintenancerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Navn som vises på beskeder og bookinger (f.eks. 'Rasmus Damgaard')",
                        max_length=100,
                        verbose_name="Visningsnavn",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Kort beskrivelse (valgfrit)",
                        max_length=500,
                        verbose_name="Om mig",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Opdateret"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bruger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brugerprofil",
                "verbose_name_plural": "Brugerprofiler",
            },
        ),
    ]
