# Generated by Django 4.2.27 on 2026-02-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeritageLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Navn på familielinjen (f.eks. 'Damgaard-linjen')",
                        max_length=50,
                        unique=True,
                        verbose_name="Navn",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Kort visningsnavn til badges (f.eks. 'Damgaard')",
                        max_length=20,
                        verbose_name="Kort navn",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Beskrivelse af denne familielinje",
                        verbose_name="Beskrivelse",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2C5F7C",
                        help_text="Hex-farvekode til kalenderbegivenheder (f.eks. '#2C5F7C')",
                        max_length=7,
                        verbose_name="Farve",
                    ),
                ),
                (
                    "badge_class",
                    models.CharField(
                        default="bg-primary",
                        help_text="Bootstrap badge klasse (f.eks. 'bg-primary', 'bg-success')",
                        max_length=30,
                        verbose_name="Badge klasse",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Visningsrækkefølge (lavere tal først)",
                        verbose_name="Rækkefølge",
                    ),
                ),
                (
                    "base_weeks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Basis ugenumre for år 0 rotation (f.eks. [26, 27])",
                        verbose_name="Baseuger",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Opdateret"),
                ),
            ],
            options={
                "verbose_name": "Familielinje",
                "verbose_name_plural": "Familielinjer",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="family_role",
            field=models.CharField(
                choices=[
                    ("member", "Medlem"),
                    ("elder", "Ældste"),
                    ("head", "Linjehoved"),
                ],
                default="member",
                help_text="Rolle i familielinjen",
                max_length=20,
                verbose_name="Familerolle",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="heritage_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Familielinje denne bruger tilhører",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="main.heritageline",
                verbose_name="Familielinje",
            ),
        ),
    ]
