# Generated by Django 4.2.27 on 2026-02-04 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0009_heritageline_userprofile_family_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservedWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Året denne reservation gælder for", verbose_name="År"
                    ),
                ),
                (
                    "week_number",
                    models.PositiveSmallIntegerField(
                        help_text="ISO ugenummer (1-53)", verbose_name="Ugenummer"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Første dag i den reserverede uge (mandag)",
                        verbose_name="Startdato",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Sidste dag i den reserverede uge (søndag)",
                        verbose_name="Slutdato",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=True,
                        help_text="Hvis låst, kan kun medlemmer af denne linje booke i denne uge",
                        verbose_name="Låst",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Admin noter om denne reservation",
                        verbose_name="Noter",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oprettet"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Opdateret"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oprettet af",
                    ),
                ),
                (
                    "heritage_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserved_weeks",
                        to="main.heritageline",
                        verbose_name="Familielinje",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserveret uge",
                "verbose_name_plural": "Reserverede uger",
                "ordering": ["year", "week_number"],
                "indexes": [
                    models.Index(
                        fields=["year", "week_number"],
                        name="main_reserv_year_1acfde_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="main_reserv_start_d_3bc9b9_idx",
                    ),
                ],
                "unique_together": {("heritage_line", "year", "week_number")},
            },
        ),
    ]
