# Generated by Django 4.2.27 on 2026-02-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_add_reserved_week_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_notification_pref",
            field=models.CharField(
                choices=[
                    ("all", "Alle notifikationer"),
                    ("mentions_only", "Kun nævnelser"),
                    ("none", "Ingen e-mailnotifikationer"),
                ],
                default="all",
                help_text="Hvornår skal du modtage e-mailnotifikationer?",
                max_length=20,
                verbose_name="E-mailnotifikationer",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_comments",
            field=models.BooleanField(
                default=True,
                help_text="Modtag notifikationer når nogen kommenterer dine beskeder",
                verbose_name="Notificer ved kommentarer",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_new_messages",
            field=models.BooleanField(
                default=True,
                help_text="Modtag notifikationer når nye beskeder postes på opslagstavlen",
                verbose_name="Notificer ved nye beskeder",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("comment", "Ny kommentar"),
                    ("booking_approved", "Booking godkendt"),
                    ("booking_rejected", "Booking afvist"),
                    ("mention", "Du blev nævnt"),
                    ("reply", "Svar på din kommentar"),
                    ("new_message", "Ny besked på opslagstavlen"),
                    ("booking_reminder", "Påmindelse om kommende booking"),
                ],
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
