# Generated by Django 4.2.27 on 2026-02-05 12:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_add_notification_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True,
                help_text="Automatisk genereret søgevektor til fuldtekstsøgning",
                null=True,
                verbose_name="Søgevektor",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="main_messag_search__49205f_gin"
            ),
        ),
    ]
