# Generated by Django 4.2.27 on 2026-05-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_add_search_vector_to_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["start_date"],
                "permissions": [
                    ("can_approve_bookings", "Can approve and reject booking requests")
                ],
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookinger",
            },
        ),
    ]
