# Generated by Django 4.2.27 on 2026-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_add_can_approve_bookings_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("booking_approved", "Booking godkendt"),
                    ("booking_rejected", "Booking afvist"),
                    ("user_activated", "Bruger aktiveret"),
                    ("user_deactivated", "Bruger deaktiveret"),
                    ("user_rejected", "Bruger afvist"),
                    ("message_deleted", "Besked slettet"),
                    ("document_uploaded", "Dokument uploadet"),
                    ("document_deleted", "Dokument slettet"),
                    ("maintenance_created", "Vedligeholdelsesanmodning oprettet"),
                    ("maintenance_updated", "Vedligeholdelsesanmodning opdateret"),
                ],
                max_length=30,
                verbose_name="Handling",
            ),
        ),
    ]
